version: '3.2'
services:
  app:
    build:
      context: ./
    tty: true
    stdin_open: true
    ports:
      - 43034:3000
    volumes:
      - ./plugins:/usr/src/redmine/plugins:cached
    environment:
      RAILS_ENV: development
      REDMINE_PLUGINS_MIGRATE: "true"
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine34
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_DATABASE: redmine34
